# server:
#   port: 9093

eureka:
  instance:
    hostname: lotus-eureka.herokuapp.com
    port: 80
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

# spring:
#     datasource:
#         driver-class-name: com.mysql.jdbc.Driver
#         password: root
#         platform: mysql
#         url: jdbc:mysql://localhost/user?verifyServerCertificate=false&useSSL=false&requireSSL=false
#         username: root
#     jpa:
#         database-platform: org.hibernate.dialect.MySQLDialect
#         generate-ddl: true
#         hibernate:
#             ddl-auto: create
#         show-sql: true

# authserver:
#   hostname: http://localhost:9092
# security:
#   oauth2:
#     resource:
#       userInfoUri: ${authserver.hostname}/user